---
title: "Lab 2: File-System, Markdown and Pandoc"
subtitle: "Stat 159, Fall 2016"
author: "Gaston Sanchez"
output: html_document
---

> ### Learning Objectives
>
> * To gain familiarity with the Shell
> * Learn basic commands to navigate the file-system
> * Learn how to express file paths: absolute and relative
> * Gain familiarity with the Markdown syntax
> * Learn how to convert markdown documents into other formats with __pandoc__

-----

### Some housekeeping

- If you work with a Mac, you're good to go.
- If you work with a Windows, make sure you have installed __git-bash__: 
[https://git-for-windows.github.io/](https://git-for-windows.github.io/)
- Another option for Windows users is to install [Win-Bash](http://win-bash.sourceforge.net/)
- First hour of this lab: command line practice
- Second hour of this lab: Markdown and Pandoc

-----


## Command Line Practice

During the first hour of the lab, work on the first 3 sections of the workshop 
[The Unix Shell](http://swcarpentry.github.io/shell-novice/) 
by _Software Carpentry_

1. [Introducing the Shell](http://swcarpentry.github.io/shell-novice/01-intro/)
2. [Files and Directories](http://swcarpentry.github.io/shell-novice/02-filedir/)
3. [Creating Things](http://swcarpentry.github.io/shell-novice/03-create/)

-----


## Markdown Practice

If you are not familiar with Markdown, you can try using one of the several 
online Markdown editors and parsers such as:

- [markdown live preview](http://markdownlivepreview.com/)
- [stackedit](https://stackedit.io/editor)
- [dillinger](http://dillinger.io/)

These are nice tools that will allow you to practice the syntax, while 
getting an idea of how the output may look like. 
Optionally, there are also markdown editors that you could downlad:

- All users: [haroopad](http://pad.haroopress.com/user.html#download)
- Mac users: [Macdown](http://macdown.uranusjr.com/)
- Windows users: [Markdownpad](http://markdownpad.com/) 


### More practice

If you are new to Markdown, you may start working on this [Interactive online markdown tutorial](http://www.markdowntutorial.com/)

If you already have some experience with Markdown, then:

- Create a new directory `stat159-markdown`, and `cd` into it.
- Create a text file, e.g. `document.md`, 
- Write some content in Markdown that includes:
	1. headings of different levels
	2. words in italics
	3. words in bold
	4. words in both italics and bold
	5. links (for urls)
	6. links for images
	7. unordered lists
	8. ordered lists
	9. lists with subitems
	10. horizontal rules 
	11. table
	12. blockquotes
	13. code blocks


-----

## Pandoc

[Pandoc](http://pandoc.org/) is a unviersal document converter. It allows you
to convert files from one markup format into another.

To convert your document into html, you will have to use __pandoc__.
From the command line, type:

```bash
# from markdown to html
pandoc -s document.md -o document.html
```

Try converting your markdown file to pdf (you need to have latex installed!):

```bash
# from markdown to pdf
pandoc document.md --latex-engine=xelatex -o document.pdf

# alternatively
pandoc document.md --latex-engine=pdflatex -o document.pdf
```

-----

## Resources

- [Learn Enough Command Line to Be Dangerous](https://www.learnenough.com/command-line-tutorial) by Michael Hartl
- [Mastering Markdown (Github guide)](https://guides.github.com/features/mastering-markdown/)
- [Pandoc Demos](http://pandoc.org/demos.html)

-----
