---
title: "HW02 - Markdown and pandoc"
subtitle: "Stat 159, Fall 2016, Prof. Sanchez"
author: "Your Name"
output: html_document
---

> ### Objectives
>
> - Work with markdown
> - Work with pandoc


Read the papers:

- [Setting the Default to Reproducible](http://stodden.net/icerm_report.pdf) 
by Stodden et al 2013

- [How to Encourage and Publish Reproducible Research](http://jelena.ece.cmu.edu/repository/conferences/07_04_Icassp_Kovacevic.pdf) 
by Jelena Kovacevic


Write an essay about reproducibility, and how to encourage and make 
it a standard. 
Name your file `stat159-hw02-first-last.md` (where "first" and "last" are
your first and last names: e.g. `stat159-hw02-gaston-sanchez.md`). 
Write your essay in markdown, and make sure to include the following elements:

1. headings of different levels
2. words in italics
3. words in bold
4. words in both italics and bold
5. links (for urls)
6. reference style links (cross-links)
7. links for images
8. unordered lists
9. ordered lists
10. lists with subitems
11. horizontal rules 
12. table
13. blockquotes
14. code blocks
15. inline code


### Convert your document into html

To convert your document into html, you will have to use __pandoc__.
From the command line, type:
```bash
# markdown to html
pandoc -s stat159-hw02-gaston-sanchez.md -o stat159-hw02-gaston-sanchez.html
```

Try converting your markdown file to pdf (you need to have latex installed!):
```bash
# markdown to pdf
pandoc stat159-hw02-gaston-sanchez.md --latex-engine=xelatex -o stat159-hw02-gaston-sanchez.pdf
```

Submit both your `.md` and `.html` documents to bCourses
