---
title: "HW02 - Git and github basics"
subtitle: "Stat 159, Fall 2016"
author: "Gaston Sanchez"
output: pdf_document
---

> ### Objectives
>
> - Work with Git and Github
> - Keep working with Markdown
> - Keep using pandoc
> - Think about a project's structure


Read the paper 
[Setting the Default to Reproducible](http://stodden.net/icerm_report.pdf) 
(by Stodden et al 2013) and write an essay about how to encourage 
reproducibility and how to make it a standard. Your content should not
exceed 5000 characters.

Write your essay in a text file using markdown syntax (do NOT use an `.Rmd` 
file). Name your file `stat159-hw02-first-last.md` (where "first" and "last" 
are your first and last names: e.g. `stat159-hw02-gaston-sanchez.md`). 



## Repository

- Create a new directory for this assignment: `stat159-hw02-first-last`
(where "first" and "last" are your first and last names: 
e.g. `stat159-hw02-gaston-sanchez`). 
- Initialize the directory as a git repository
- Create a subdirectory `paper`
- Create a subdirectory `images`
- Write your paper in a text file using markdown syntax. 
- Include a script file `create-doc.txt` with the commands to generate
reports with pandoc
- Include a `README.md` file describing the project
- Practice writing good commit messages
- Don't be afraid of undoing things



The file-structure of your project should look like this:

```
project/
	.gitignore
	README.md
	create-doc.txt
	paper/
		sections/
			00-abstract.md
			01-introduction.md
			02-discussion.md
			03-conclusions.md
		paper.md
	images/
		git-logo.png
		stat159-logo.png
		markdown-logo.png
```

## Paper Requirements

Please make sure to include the following elements in your paper:

1. headings of different levels
2. words in italics
3. words in bold
4. words in both italics and bold
5. unordered list
6. ordered list
7. list with subitems
8. horizontal rule 
9. table
10. blockquote
11. code block
12. link (for urls)
13. Image: use "The Difference" xkcd cartoon 
[http://imgs.xkcd.com/comics/the_difference.png](http://imgs.xkcd.com/comics/the_difference.png) as an image to include in your essay.
