---
title: "HW04 - Intro to Dynamic Documents"
subtitle: "Stat 159, Fall 2016"
author: "Gaston Sanchez"
output: html_document
---

> ### Objectives
>
> - Work with Rmd files
> - Work with Make


The purpose of this homework is to use a dynamic document in order to perform 
a regression analysis and reproduce the main results published in the book 
[An Introduction to Statistical Learning](http://www-bcf.usc.edu/~gareth/ISL/data.html), 
__Section 3.2 Multiple Linear Regression__ (Chapter 3. Linear Regression).


### Project Structure

Use the following file structure for your project (as a github repository)

```
linear-regression/
	data/
		Advertising.csv
	report/
		report.Rmd
		report.html
	.gitignore
	LICENSE
	Makefile
	README.md
```


### Data

The example in the book uses the data set `Advertising`, which is available at: 
[http://www-bcf.usc.edu/~gareth/ISL/Advertising.csv](http://www-bcf.usc.edu/~gareth/ISL/Advertising.csv)


### Multiple Linear Regression Analysis

Take a look at the section 3.2 (pages 71-82).

In your `.Rmd` file, open code chunks and write code to perform the 
tasks listed below.

__Import Data.__ 
Read the dataset in R, and inspect the data frame. Check 
its structure, dimensions, take a peek, etc.

__Exploratory Analysis.__ 
Get a histogram and boxplot, as well as summary statistics for all variables. 
Likewise, compute the correlation matrix between all the variables.
Are all predictor variables linearly correlated with `Sales`?

__Regression Model.__
Use the function `lm()` to regress `Sales` onto `TV`, `Radio` and `Newspaper`

$$
Sales = \beta_0 + \beta_1 \times TV + \beta_2 \times Radio + \beta_3 \times Newspaper
$$

Confirm that the regression coefficients are: $\beta_0$ = 2.939, 
$\beta_1$ = 0.046, $\beta_2$ = 0.189, and $\beta_3$ = -0.001.

__Residual Sum of Squares.__ 
Use the `residuals` of the `"lm"` object and write code to calculate the RSS 
(Residual Sum of Squares). Use the RSS formula of eq. 3.16 (see page 69).

__Residual Standard Error.__
Write code to calculate the RSE (Residual Standard Error) according to the 
formula of eq. 3.25 (see page 80)

__Confidence Interval for Coefficients.__
Use the function `confint()` to obtain the 95% confidence intervals of
the regression coefficients.


#### Reproduced Results

You should reproduce the following material from chapter 3, section 3.2

- Figure 3.1 (page 62): Regression line with data points
- Table 3.4 (page 74): Coefficients of the least squares model
- Table 3.5 (page 75): Correlation matrix
- Table 3.6 (page 76): RSE, R2 and F-statistics of the least squares model


### Report

Write a report (in an `.Rmd` file) with the following sections:

1. Abstract
2. Introduction
3. Data
4. Exploratory Data Analysis
5. Model
6. Results
7. Conclusions


### Makefile

Your Makefile should include the following rules:

- `make data`: downloads the `Advertising.csv` data file in the `data/` directory
- `make report`: creates a report in pdf and html under the `report/` directory
- `make clean`: removes secondary outputs in report

-----
