---
title: "HW04 - Stat 159, Fall 2016"
output: html_document
---

> ### Objectives
> - Work with Git
> - Work with Make


### Your first reproducible project

This HW assignment involves writing a paper/document about the tools
we've covered so far, and describe in your words how you work on your 
assignment (tell us about your experience):

- Explain what is a Makefile
- Explain the role that a Makefile plays in the RR workflow
- Explain what is Git, and its role in RR
- Explain what is pandoc
- Explain what is markdown
- Write a narrative about how you worked our this project
- What resources you used to get the job done.
- What were the "easy" parts?
- What were the challenging parts?
- What things you were stuck with?
- Did you work with and/or get help from someone else?
- How much time did it take?


### Instructions

- Create a new directory
- Add a `.gitignore` file
- Initialize the directory with Git
- Create the file structure:

```
project/
	- .gitignore
	- README.md
	- paper/
		- sections/
			- 00-abstract.md
			- 01-introduction.md
			- 02-intermediate.md
			- 03-conclusions.md
		- paper.md
	- images/
		- git.png
		- makefile.png
		- markdown.png
	- Makefile
```

- Create a remote repository in your Github account
- Push your project to github
- Practice writing good commit messages
- Don't be afraid of undo things


After running `make`, your project should look like this:

```
project/
	- .gitignore
	- README.md
	- paper/
		- sections/
			- 00-abstract.md
			- 01-introduction.md
			- 02-intermediate.md
			- 03-conclusions.md
		- paper.Rmd
		- paper.html  (output)
		- paper.pdf  (output)
	- images/
		- git.png
		- makefile.png
		- markdown.png
	- Makefile
```

